os:
  - linux

env:
  - WINEARCH=win32
  - WINEARCH=win64
  - WINEARCH="" # WoW64
  - NOCHECK="--nocheck"
  - WINEARCH=win32 CACHE="--cache https://dl.dropboxusercontent.com/u/38458267/msys2/msys2-pack-20150512_v1_i686.tar.gz"
  - WINEARCH=win64 CACHE="--cache https://dl.dropboxusercontent.com/u/38458267/msys2/msys2-pack-20150512_v1_x86_64.tar.gz"


cache: apt

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 800x600x16"

before_script:
  - sudo add-apt-repository -y ppa:pipelight/daily
  - sudo apt-get update -qq
  - sudo apt-get install -y --install-recommends wine-staging wine-staging-compat
  - MSYS2_SCRIPTS_DEB=msys2-scripts_20150811_all.deb
    #  - wget https://github.com/fracting/msys2-scripts-deb/raw/master/${MSYS2_SCRIPTS_DEB}
  - sudo dpkg -i ${MSYS2_SCRIPTS_DEB}

language: c

compiler:
  - gcc

script:
  - msys2-init ${CACHE}
  - msys2-pack v1
    #  - svn co https://github.com/fracting/MSYS2-packages/trunk/xz
    #  - cd xz
    #  - msys2-shell -c "makepkg -s -f --noconfirm --skippgpcheck ${NOCHECK}"

deploy:
  provider: s3
  access_key_id: "AKIAI332BORZKTHFBYBA"
  secret_access_key: "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"
  bucket: "fracting/msys2/pack"
  skip_cleanup: true
  local_dir: ${HOME}/msys2-pack
